[platformio]
default_envs = prusa_drucker_4

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit Protomatter @ ^1.7.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0

build_flags = 
    -I include
    -D WIFI_SSID_ENV=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASS_ENV=\"${sysenv.WIFI_PASS}\"

[env:prusa_drucker_4]
build_flags = 
    ${env.build_flags}
    -D PRUSA_PRINTER_4
    -D CONFIG_NAME_STR=\"Drucker\ 4\"
    -D PRINTER_IP=\"10.30.0.74\" 
    -D PRUSA_API_KEY=\"${sysenv.PRUSA_API_KEY_D4}\"

[env:prusa_drucker_5]
build_flags = 
    ${env.build_flags}
    -D PRUSA_PRINTER_5
    -D CONFIG_NAME_STR=\"Drucker\ 5\"
    -D PRINTER_IP=\"10.30.0.75\" 
    -D PRUSA_API_KEY=\"${sysenv.PRUSA_API_KEY_D5}\"