[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/Adafruit Protomatter @ ^1.7.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/chunkysteveo/OctoPrintAPI.git
build_flags = 
    -I include
    -D WIFI_SSID_ENV=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASS_ENV=\"${sysenv.WIFI_PASS}\"

[env:drucker_1]
build_flags = 
    ${env.build_flags} 
    -D PRINTER_IP=\"10.30.0.138\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D1}\"

[env:drucker_2]
build_flags = 
    ${env.build_flags} 
    -D PRINTER_IP=\"10.30.0.140\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D2}\"

[env:drucker_3]
build_flags = 
    ${env.build_flags} 
    -D PRINTER_IP=\"10.30.0.142\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D3}\"