[env:esp32-s3-devkitc-1] ; Beispiel für ein S3 Board, falls zutreffend
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit Protomatter @ ^1.7.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0
    # Einbindung direkt via GitHub URL:
    https://github.com/chunkysteveo/OctoPrintAPI.git
    
build_flags = 
    -I include
    
