[platformio]
# Standardordner für dieses Projekt
default_envs = drucker_1

[env]
# Gemeinsame Basis-Konfiguration für alle Drucker
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Fixierung der Bibliotheken auf stabile Versionen
lib_deps =
    adafruit/Adafruit Protomatter @ ^1.7.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0
    # Fixierung auf den stabilen Git-Tag v1.1.6
    https://github.com/chunkysteveo/OctoPrintAPI.git#1.1.6

build_flags = 
    -I include
    # Falls lokal keine secret.h da ist, nutzt das CI diese sysenv-Variablen
    -D WIFI_SSID_ENV=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASS_ENV=\"${sysenv.WIFI_PASS}\"

# --- Instanz: Drucker 1 ---
[env:drucker_1]
build_flags = 
    ${env.build_flags} 
    -D DRUCKER_1 
    -D PRINTER_IP=\"10.30.0.138\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D1}\"

# --- Instanz: Drucker 2 ---
[env:drucker_2]
build_flags = 
    ${env.build_flags} 
    -D DRUCKER_2 
    -D PRINTER_IP=\"10.30.0.140\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D2}\"

# --- Instanz: Drucker 3 ---
[env:drucker_3]
build_flags = 
    ${env.build_flags} 
    -D DRUCKER_3 
    -D PRINTER_IP=\"10.30.0.142\" 
    -D PRINTER_API_KEY=\"${sysenv.API_KEY_D3}\"